# Generated by Django 4.2.22 on 2025-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source", models.TextField()),
                ("external_id", models.TextField()),
                ("response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.UniqueConstraint(fields=("source", "external_id"), name="unique_source_external_id"),
        ),
    ]
