# Generated by Django 4.2.22 on 2025-08-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kestrel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="manual_label",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="predicted_label",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="record",
            name="predicted_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
