def extract_text_features(source, response):
    match source:
        case "muckrock_foia":
            # The first email's subject and body are the most relevant. Later emails are noisy and numerous,
            # even after excluding `autogenerated` emails. If adding others, it might be best to have separate
            # features for emails from/to the user.
            #
            # Record title and tags are assigned by users and not sent to agencies, and therefore might be
            # confounders. Other fields are either irrelevant (like dates), noisy (like filenames) or often
            # missing (like file descriptions).
            if communications := response["communications"]:
                # TODO(james): A FeatureUnion could be used to keep the fields distinct.
                # https://github.com/open-contracting/kestrel/issues/3
                return f"{communications[0]['subject']} {communications[0]['communication']}"
            return ""
        case _:
            raise NotImplementedError(f"extract_text_features() not implemented for source {source!r}")
